In [1]:
import numpy as np

In [2]:
lista1 = [1,2,3,4,5,6,5]

In [3]:
lista1.index(2)

1

In [4]:
lista1.index(5)

4

### E no numpy?

In [5]:
arr1 = np.array(lista1)

In [6]:
arr1

array([1, 2, 3, 4, 5, 6, 5])

In [7]:
arr1.index(3)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [11]:
np.where(arr1==3)

(array([2], dtype=int64),)

In [20]:
indice3 = np.where(arr1==3)
indice3

(array([2], dtype=int64),)

In [23]:
indice3 = np.where(arr1==3)[0]
indice3

array([2], dtype=int64)

In [24]:
indice3 = np.where(arr1==3)[0][0]
indice3

2

In [12]:
np.where(arr1<3)

(array([0, 1], dtype=int64),)

In [13]:
np.where(arr1==5)

(array([4, 6], dtype=int64),)

In [14]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,2]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

In [18]:
np.where(arr2 == 6)

(array([1], dtype=int64), array([2], dtype=int64))

In [19]:
np.where(arr2 == 2)

(array([0, 2], dtype=int64), array([1, 2], dtype=int64))